version: "3.9"

services:

  redis:
    extends:
      file: docker-compose.dependencies.yml
      service: redis

  mongodb:
    extends:
      file: docker-compose.dependencies.yml
      service: mongodb

  nbi:
    extends:
      file: docker-compose.common.yml
      service: genieacs
    ports:
      - 7557:7777
    command:
      - genieacs-nbi
