version: "3.9"

services:

  mongodb:
    image: mongo

  cwmp:
    depends_on:
      - mongodb
    extends:
      file: docker-compose.common.yml
      service: genieacs
    ports:
      - 7457:7777
    command:
      - genieacs-cwmp

  nbi:
    depends_on:
      - mongodb
    extends:
      file: docker-compose.common.yml
      service: genieacs
    ports:
      - 7557:7777
    command:
      - genieacs-nbi

  fs:
    depends_on:
      - mongodb
    extends:
      file: docker-compose.common.yml
      service: genieacs
    ports:
      - 7577:7777
    command:
      - genieacs-fs
